export const questions = [
    {
      id: 1,
      category: "Physical Appearance",
      question: "What is your ideal hair color for your boyfriend?",
      type: "multiple-choice",
      options: ["Blonde", "Brown", "Black", "Dyed Colorful", "Ginger", "Bald"],
    },
    {
      id: 2,
      category: "Physical Appearance",
      question: "What hairstyle do you prefer?",
      type: "multiple-choice",
      options: [
        "Short and curly",
        "Short and straight",
        "Long and curly",
        "Long and straight",
        "Buzz Cut",
        "Afro",
        "Dreadlocks"
      ],
    },
    {
      id: 3,
      category: "Physical Appearance",
      question: "What eye color is most attractive to you?",
      type: "multiple-choice",
      options: ["Blue", "Green", "Brown", "Hazel", "Gray", "Heterochromia"],
    },
    {
      id: 4,
      category: "Physical Appearance",
      question: "What is your preferred height for your boyfriend?",
      type: "multiple-choice",
      options: ["Tall", "Average", "Short"],
    },
    {
      id: 5,
      category: "Physical Appearance",
      question: "What body type do you find most appealing?",
      type: "multiple-choice",
      options: ["Athletic", "Average", "Muscular", "Slim", "Plus-size"],
    },
    {
      id: 6,
      category: "Physical Appearance",
      question: "How would you describe his facial features?",
      type: "multiple-choice",
      options: ["Sharp", "Soft", "Chiseled", "Boyish", "Rugged", "Expressive"],
    },
    {
      id: 7,
      category: "Physical Appearance",
      question: "What type of fashion does he wear?",
      type: "multiple-choice",
      options: [
        "Casual",
        "Sporty",
        "Trendy",
        "Formal",
        "Edgy",
        "Minimalist",
        "Preppy",
        "Vintage",
        "Business Casual",
        "Outdoorsy",
      ],
    },
    {
      id: 8,
      category: "Personality Traits",
      question: "What type of humor do you prefer?",
      type: "check-box",
      options: [
        "Witty",
        "Dry",
        "Goofy",
        "Sarcastic",
        "Offensive and dark",
        "Self-deprecating",
        "Pun-filled",
        "Quirky",
      ],
    },
    {
      id: 9,
      category: "Personality Traits",
      question: "What hobbies would you like him to have?",
      type: "check-box",
      options: [
        "Reading",
        "Sports",
        "Gaming",
        "Cooking",
        "Traveling",
        "Music",
        "Photography",
        "Art",
        "Gym",
        "Outdoor activities",
        "Film buff",
      ],
    },
    {
      id: 10,
      category: "Personality Traits",
      question: "What communication style do you prefer?",
      type: "multiple-choice",
      options: [
        "Straightforward",
        "Thoughtful",
        "Playful",
        "Deep conversations",
        "Empathetic",
        "Funny but insightful",
        "Supportive listener",
        "Philosophical",
        "Flirty",
        "Direct but compassionate",
      ],
    },
    {
      id: 11,
      category: "Personality Traits",
      question: "What is his love language?",
      type: "multiple-choice",
      options: [
        "Words of affirmation",
        "Acts of service",
        "Gift-giving",
        "Quality time",
        "Physical touch",
        "Shared experiences",
      ],
    },
    {
      id: 12,
      category: "Personality Traits",
      question: "How intelligent should he be?",
      type: "multiple-choice",
      options: [
        "Book-smart",
        "Street-smart",
        "Creative",
        "Emotionally intelligent",
        "Philosophical",
        "Practical knowledge",
      ],
    },
    {
      id: 14,
      category: "Personality Traits",
      question: "What career or life goals do you envision for him?",
      type: "multiple-choice",
      options: [
        "Ambitious professional",
        "Creative artist",
        "Laid-back",
        "Entrepreneur",
        "Philanthropist",
        "World traveler",
        "Social advocate",
      ],
    },
    {
      id: 15,
      category: "Personality Traits",
      question: "How social is he?",
      type: "multiple-choice",
      options: ["Introverted", "Extroverted", "Balance of both"],
    },
  ];
  
  export default questions;

  